import uuid
from sqlalchemy import Column, String, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from app.database import Base

class User(Base):
    __tablename__ = "users"

    # Secure, random UUID primary key generated by Python
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    # Strict length constraints as requested (1-20 alphabets)
    first_name = Column(String(20), nullable=False)
    
    # Strict length constraints as requested (1-15 alphabets)
    last_name = Column(String(15), nullable=False)
    
    # Email is stored lowercase in the DB to prevent case-sensitivity duplicates
    email = Column(String(100), unique=True, nullable=False, index=True)
    
    # Bcrypt hashed password (never store plain text!)
    hashed_password = Column(String(255), nullable=False)
    
    # Automatic timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
